local beltlikes_drive_resistance_mapping = require("compatibility.mods.planetaris-arig.beltlikes_drive_resistance_mapping")

local CompatibilityDataStartStagePlanetarisHyarion = {}

function CompatibilityDataStartStagePlanetarisHyarion.apply()
  DisasterCore_Belts_DataGlobals.Beltlike.extend_beltlikes_drive_resistance_mapping(beltlikes_drive_resistance_mapping)
end

return CompatibilityDataStartStagePlanetarisHyarion